apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: tomcat
      labels:
        app: myapp
    spec:
      containers:
        - name: tomcat-app
          image: sanjay7917/tomcat
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 8080